<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.361">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Investments - Portfolio Optimization: Finding the Best Combination of Risky Assets</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item">
      Investments
      </li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Investments</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../schedule.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Schedule</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../syllabus.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Syllabus</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Lectures</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Lecture 1: The Investment Environment</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture01/lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pre-class Reading</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Lecture 2: Foundations of Financial Markets</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture02/lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pre-class Reading</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture02/lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false">
 <span class="menu-text">Lecture 3: Measuring and Comparing Returns</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture03/lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pre-class Reading</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture03/lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Lecture 4: Measuring Risk and Expected Return</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture04/lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pre-class Reading</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture04/lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Lecture 5: Portfolio Risk and Returns</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture05/lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pre-class Reading</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture05/lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false">
 <span class="menu-text">Lecture 6: Optimal Capital Allocation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-7" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-7" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture06/lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pre-class Reading</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture06/lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false">
 <span class="menu-text">Lecture 7: Mean-Variance Portfolio Optimization</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-8" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-8" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture07/lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pre-class Reading</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture07/lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false">
 <span class="menu-text">Lecture 8: Optimal Asset Allocation</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-9" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-9" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture08/lecture.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Pre-class Reading</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture08/lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab</span></a>
  </div>
</li>
      </ul>
  </li>
          <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false">
 <span class="menu-text">Lecture 9: Review Session</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-10" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-10" class="collapse list-unstyled sidebar-section depth2 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../lectures/lecture09/lab.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Lab</span></a>
  </div>
</li>
      </ul>
  </li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#portfolio-optimization-with-two-risky-assets" id="toc-portfolio-optimization-with-two-risky-assets" class="nav-link" data-scroll-target="#portfolio-optimization-with-two-risky-assets"><span class="header-section-number">2</span> Portfolio Optimization with Two Risky Assets</a>
  <ul class="collapse">
  <li><a href="#the-investment-opportunity-set" id="toc-the-investment-opportunity-set" class="nav-link" data-scroll-target="#the-investment-opportunity-set"><span class="header-section-number">2.1</span> The Investment Opportunity Set</a></li>
  <li><a href="#the-optimal-risky-portfolio-tangency-portfolio" id="toc-the-optimal-risky-portfolio-tangency-portfolio" class="nav-link" data-scroll-target="#the-optimal-risky-portfolio-tangency-portfolio"><span class="header-section-number">2.2</span> The Optimal Risky Portfolio (Tangency Portfolio)</a></li>
  </ul></li>
  <li><a href="#portfolio-optimization-with-an-arbitrary-number-of-risky-assets" id="toc-portfolio-optimization-with-an-arbitrary-number-of-risky-assets" class="nav-link" data-scroll-target="#portfolio-optimization-with-an-arbitrary-number-of-risky-assets"><span class="header-section-number">3</span> Portfolio Optimization with an Arbitrary Number of Risky Assets</a>
  <ul class="collapse">
  <li><a href="#matrix-notation-for-portfolio-inputs" id="toc-matrix-notation-for-portfolio-inputs" class="nav-link" data-scroll-target="#matrix-notation-for-portfolio-inputs"><span class="header-section-number">3.1</span> Matrix Notation for Portfolio Inputs</a></li>
  <li><a href="#the-tangency-portfolio-with-n-assets" id="toc-the-tangency-portfolio-with-n-assets" class="nav-link" data-scroll-target="#the-tangency-portfolio-with-n-assets"><span class="header-section-number">3.2</span> The Tangency Portfolio with N Assets</a></li>
  </ul></li>
  <li><a href="#key-takeaways" id="toc-key-takeaways" class="nav-link" data-scroll-target="#key-takeaways"><span class="header-section-number">4</span> Key Takeaways</a></li>
  <li><a href="#key-formulas-summary" id="toc-key-formulas-summary" class="nav-link" data-scroll-target="#key-formulas-summary"><span class="header-section-number">5</span> Key Formulas Summary</a></li>
  <li><a href="#practice-problems" id="toc-practice-problems" class="nav-link" data-scroll-target="#practice-problems"><span class="header-section-number">6</span> Practice Problems</a></li>
  <li><a href="#ask-an-llm" id="toc-ask-an-llm" class="nav-link" data-scroll-target="#ask-an-llm"><span class="header-section-number">7</span> Ask an LLM</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Portfolio Optimization: Finding the Best Combination of Risky Assets</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>When you have access to multiple risky assets, a natural question emerges: how should you combine them to create the best possible portfolio? For investors who care about expected returns and volatility—mean-variance optimizers—“best” has a precise meaning: the portfolio that delivers the highest expected return per unit of risk, which is the portfolio with the <strong>maximum Sharpe ratio</strong>. This portfolio goes by several names: the <strong>optimal risky portfolio</strong>, the <strong>tangency portfolio</strong>, or simply the <strong>maximum Sharpe ratio portfolio</strong>.</p>
<p>The tangency portfolio concept is foundational to modern portfolio theory because it represents the single best combination of risky assets available to any investor, regardless of how risk-averse they are. A highly conservative investor and an aggressive risk-taker will both want to hold the same tangency portfolio—they will simply differ in how much of their total wealth they allocate to this risky portfolio versus a risk-free asset. This separation between finding the optimal risky portfolio and deciding how much risk to take is one of the most elegant results in finance theory, and we will explore it more deeply in subsequent lectures.</p>
<p>This lecture develops the mechanics of portfolio optimization in two stages. We begin with the simplest possible case—combining just two risky assets—which allows us to build intuition through graphical analysis and relatively simple formulas. We then extend these ideas to the general case with an arbitrary number of assets, where matrix algebra becomes essential for managing the complexity. By the end of this lecture, you should be able to construct an optimal risky portfolio from any set of assets and understand why this optimal portfolio is independent of investor preferences.</p>
</section>
<section id="portfolio-optimization-with-two-risky-assets" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="portfolio-optimization-with-two-risky-assets"><span class="header-section-number">2</span> Portfolio Optimization with Two Risky Assets</h2>
<p>We start with the simplest scenario: you have access to exactly two risky assets, which we’ll call Asset A and Asset B. To construct portfolios from these assets, you need three types of inputs that describe their risk-return characteristics. First, you need the expected returns of each asset, denoted <span class="math inline">\(E[R_A]\)</span> and <span class="math inline">\(E[R_B]\)</span>. Second, you need a measure of each asset’s standalone risk, captured by their standard deviations <span class="math inline">\(\sigma_A\)</span> and <span class="math inline">\(\sigma_B\)</span>. Third—and this is what makes portfolio theory interesting—you need to know how the two assets move together, captured by their covariance <span class="math inline">\(\text{Cov}(R_A, R_B)\)</span>.</p>
<p>The portfolio construction problem reduces to choosing a single number: <span class="math inline">\(w_A\)</span>, the fraction of your portfolio invested in Asset A. Once you’ve chosen <span class="math inline">\(w_A\)</span>, the fraction in Asset B is automatically determined as <span class="math inline">\(w_B = 1 - w_A\)</span>. If <span class="math inline">\(w_A = 0.6\)</span>, for example, you’re putting 60% of your money in Asset A and 40% in Asset B. Your goal is to find the value of <span class="math inline">\(w_A\)</span> that maximizes the Sharpe ratio of the resulting portfolio. Before we solve this optimization problem directly, it’s instructive to visualize what different portfolio combinations look like in risk-return space.</p>
<section id="the-investment-opportunity-set" class="level3" data-number="2.1">
<h3 data-number="2.1" class="anchored" data-anchor-id="the-investment-opportunity-set"><span class="header-section-number">2.1</span> The Investment Opportunity Set</h3>
<p>The <strong>investment opportunity set</strong> consists of all possible portfolios you can create by varying the weights <span class="math inline">\(w_A\)</span> and <span class="math inline">\(w_B\)</span>. Since there are infinitely many possible weight combinations, the investment opportunity set is infinite—but we can visualize its shape by computing a representative sample of portfolios.</p>
<p>For any choice of weights, the expected return and variance of the resulting portfolio are given by:</p>
<p><span class="math display">\[E[R_P] = w_A E[R_A] + w_B E[R_B]\]</span></p>
<p><span class="math display">\[\text{Var}(R_P) = w_A^2 \text{Var}(R_A) + w_B^2 \text{Var}(R_B) + 2 w_A w_B \text{Cov}(R_A, R_B)\]</span></p>
<p>where <span class="math inline">\(w_B = 1 - w_A\)</span>. The portfolio’s standard deviation is simply <span class="math inline">\(\sigma_P = \sqrt{\text{Var}(R_P)}\)</span>.</p>
<p>Notice that the expected return formula is straightforward: portfolio expected return is just a weighted average of the individual expected returns. The variance formula, however, contains that crucial third term involving covariance. This is where diversification benefits come from—when assets don’t move in perfect lockstep, combining them produces a portfolio with less variance than a simple weighted average of individual variances would suggest.</p>
<p>When we plot these portfolios with standard deviation on the horizontal axis and expected return on the vertical axis, we get a curve that typically bows to the left. This curvature represents the power of diversification: by combining assets that aren’t perfectly correlated, we can achieve risk-return combinations that would be impossible with either asset alone.</p>
<p><strong>Example 1: Constructing the Investment Opportunity Set</strong></p>
<p><em>You are considering investing in Facebook (FB) and Netflix (NFLX). Based on your analysis, you estimate that Facebook has an expected return of 10% with a standard deviation of 20%, while Netflix has an expected return of 15% with a standard deviation of 25%. The covariance between their returns is 0.02, and the risk-free rate is 5%. Construct 21 different portfolios by varying the weight in Facebook from 0% to 100% in increments of 5%. For each portfolio, calculate the expected return, standard deviation, and Sharpe ratio.</em></p>
<div class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-1-contents" aria-controls="callout-1" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-1" class="callout-1-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>We’ll systematically work through several representative portfolios to illustrate the calculations.</p>
<p><strong>Given information:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>Facebook (FB)</th>
<th>Netflix (NFLX)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Expected Return</td>
<td><span class="math inline">\(E[R_{FB}] = 10\%\)</span></td>
<td><span class="math inline">\(E[R_{NFLX}] = 15\%\)</span></td>
</tr>
<tr class="even">
<td>Standard Deviation</td>
<td><span class="math inline">\(\sigma_{FB} = 20\%\)</span></td>
<td><span class="math inline">\(\sigma_{NFLX} = 25\%\)</span></td>
</tr>
<tr class="odd">
<td>Covariance</td>
<td><span class="math inline">\(\text{Cov}(R_{FB}, R_{NFLX}) = 0.02\)</span></td>
<td></td>
</tr>
<tr class="even">
<td>Risk-free rate</td>
<td><span class="math inline">\(R_f = 5\%\)</span></td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Portfolio calculations for selected weights:</strong></p>
<p><em>Portfolio 1: <span class="math inline">\(w_{FB} = 0\%\)</span>, <span class="math inline">\(w_{NFLX} = 100\%\)</span> (all Netflix)</em></p>
<p><span class="math display">\[E[R_P] = 0 \times 0.10 + 1 \times 0.15 = 0.15 = 15\%\]</span></p>
<p><span class="math display">\[\text{Var}(R_P) = 0^2 \times 0.20^2 + 1^2 \times 0.25^2 + 2 \times 0 \times 1 \times 0.02 = 0.0625\]</span></p>
<p><span class="math display">\[\sigma_P = \sqrt{0.0625} = 0.25 = 25\%\]</span></p>
<p><span class="math display">\[\text{Sharpe Ratio} = \frac{0.15 - 0.05}{0.25} = 0.40\]</span></p>
<p><em>Portfolio 2: <span class="math inline">\(w_{FB} = 40\%\)</span>, <span class="math inline">\(w_{NFLX} = 60\%\)</span></em></p>
<p><span class="math display">\[E[R_P] = 0.40 \times 0.10 + 0.60 \times 0.15 = 0.04 + 0.09 = 0.13 = 13\%\]</span></p>
<p><span class="math display">\[\text{Var}(R_P) = 0.40^2 \times 0.04 + 0.60^2 \times 0.0625 + 2 \times 0.40 \times 0.60 \times 0.02\]</span></p>
<p><span class="math display">\[= 0.0064 + 0.0225 + 0.0096 = 0.0385\]</span></p>
<p><span class="math display">\[\sigma_P = \sqrt{0.0385} = 0.1962 = 19.62\%\]</span></p>
<p><span class="math display">\[\text{Sharpe Ratio} = \frac{0.13 - 0.05}{0.1962} = 0.408\]</span></p>
<p><em>Portfolio 3: <span class="math inline">\(w_{FB} = 100\%\)</span>, <span class="math inline">\(w_{NFLX} = 0\%\)</span> (all Facebook)</em></p>
<p><span class="math display">\[E[R_P] = 1 \times 0.10 + 0 \times 0.15 = 0.10 = 10\%\]</span></p>
<p><span class="math display">\[\sigma_P = 0.20 = 20\%\]</span></p>
<p><span class="math display">\[\text{Sharpe Ratio} = \frac{0.10 - 0.05}{0.20} = 0.25\]</span></p>
<p><strong>Complete results for all 21 portfolios:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th><span class="math inline">\(w_{FB}\)</span></th>
<th><span class="math inline">\(w_{NFLX}\)</span></th>
<th><span class="math inline">\(E[R_P]\)</span></th>
<th><span class="math inline">\(\sigma_P\)</span></th>
<th>Sharpe Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0%</td>
<td>100%</td>
<td>15.00%</td>
<td>25.00%</td>
<td>0.400</td>
</tr>
<tr class="even">
<td>5%</td>
<td>95%</td>
<td>14.75%</td>
<td>24.02%</td>
<td>0.406</td>
</tr>
<tr class="odd">
<td>10%</td>
<td>90%</td>
<td>14.50%</td>
<td>23.08%</td>
<td>0.411</td>
</tr>
<tr class="even">
<td>15%</td>
<td>85%</td>
<td>14.25%</td>
<td>22.18%</td>
<td>0.417</td>
</tr>
<tr class="odd">
<td>20%</td>
<td>80%</td>
<td>14.00%</td>
<td>21.33%</td>
<td>0.422</td>
</tr>
<tr class="even">
<td>25%</td>
<td>75%</td>
<td>13.75%</td>
<td>20.54%</td>
<td>0.426</td>
</tr>
<tr class="odd">
<td>30%</td>
<td>70%</td>
<td>13.50%</td>
<td>19.80%</td>
<td>0.429</td>
</tr>
<tr class="even">
<td>35%</td>
<td>65%</td>
<td>13.25%</td>
<td>19.14%</td>
<td>0.431</td>
</tr>
<tr class="odd">
<td>40%</td>
<td>60%</td>
<td>13.00%</td>
<td>18.54%</td>
<td>0.432</td>
</tr>
<tr class="even">
<td>45%</td>
<td>55%</td>
<td>12.75%</td>
<td>18.02%</td>
<td>0.430</td>
</tr>
<tr class="odd">
<td>50%</td>
<td>50%</td>
<td>12.50%</td>
<td>17.58%</td>
<td>0.426</td>
</tr>
<tr class="even">
<td>55%</td>
<td>45%</td>
<td>12.25%</td>
<td>17.23%</td>
<td>0.421</td>
</tr>
<tr class="odd">
<td>60%</td>
<td>40%</td>
<td>12.00%</td>
<td>16.97%</td>
<td>0.412</td>
</tr>
<tr class="even">
<td>65%</td>
<td>35%</td>
<td>11.75%</td>
<td>16.81%</td>
<td>0.402</td>
</tr>
<tr class="odd">
<td>70%</td>
<td>30%</td>
<td>11.50%</td>
<td>16.76%</td>
<td>0.388</td>
</tr>
<tr class="even">
<td>75%</td>
<td>25%</td>
<td>11.25%</td>
<td>16.80%</td>
<td>0.372</td>
</tr>
<tr class="odd">
<td>80%</td>
<td>20%</td>
<td>11.00%</td>
<td>16.95%</td>
<td>0.354</td>
</tr>
<tr class="even">
<td>85%</td>
<td>15%</td>
<td>10.75%</td>
<td>17.20%</td>
<td>0.334</td>
</tr>
<tr class="odd">
<td>90%</td>
<td>10%</td>
<td>10.50%</td>
<td>17.55%</td>
<td>0.313</td>
</tr>
<tr class="even">
<td>95%</td>
<td>5%</td>
<td>10.25%</td>
<td>18.00%</td>
<td>0.292</td>
</tr>
<tr class="odd">
<td>100%</td>
<td>0%</td>
<td>10.00%</td>
<td>18.54%</td>
<td>0.270</td>
</tr>
</tbody>
</table>
<p>Notice several key patterns in these results. First, the portfolio with the highest Sharpe ratio (approximately 0.432) occurs around <span class="math inline">\(w_{FB} = 40\%\)</span>—neither asset alone achieves this level of risk-adjusted performance. Second, the minimum variance portfolio occurs around <span class="math inline">\(w_{FB} = 70\%\)</span>, where <span class="math inline">\(\sigma_P \approx 16.76\%\)</span>—this is lower than either individual asset’s volatility, demonstrating the power of diversification. Third, when plotted in mean-volatility space, these portfolios trace out a curve that bows to the left, with the tangency portfolio located on the upper portion of this curve.</p>
</div>
</div>
</div>
</section>
<section id="the-optimal-risky-portfolio-tangency-portfolio" class="level3" data-number="2.2">
<h3 data-number="2.2" class="anchored" data-anchor-id="the-optimal-risky-portfolio-tangency-portfolio"><span class="header-section-number">2.2</span> The Optimal Risky Portfolio (Tangency Portfolio)</h3>
<p>The optimal risky portfolio—the combination of Assets A and B that maximizes the Sharpe ratio—can be found analytically. The weight in Asset A that achieves this maximum is:</p>
<p><span class="math display">\[w_A = \frac{(E[R_A] - R_f) \sigma_B^2 - (E[R_B] - R_f)\text{Cov}(R_A, R_B)}{(E[R_A] - R_f) \sigma_B^2 + (E[R_B] - R_f) \sigma_A^2 - (E[R_A] - R_f + E[R_B] - R_f)\text{Cov}(R_A, R_B)}\]</span></p>
<p>with <span class="math inline">\(w_B = 1 - w_A\)</span>.</p>
<p>This formula, while complex, has an intuitive structure. The numerator and denominator both involve risk premia (<span class="math inline">\(E[R] - R_f\)</span>), variances, and the covariance between assets. The formula essentially balances the attractiveness of each asset (its excess return) against its contribution to portfolio risk and how it interacts with the other asset.</p>
<p>We call this the “tangency portfolio” because of its geometric interpretation. If you draw a line from the risk-free rate on the vertical axis to any point on the investment opportunity set curve, the slope of that line equals the Sharpe ratio of that portfolio. The tangency portfolio is the point where this line achieves its steepest slope—that is, where the line is tangent to the curve. This tangent line is the Capital Allocation Line (CAL) for this optimal risky portfolio.</p>
<p><strong>Example 2: Finding the Tangency Portfolio</strong></p>
<p><em>Using the Facebook and Netflix data from Example 1 (expected returns of 10% and 15%, standard deviations of 20% and 25%, covariance of 0.02, and risk-free rate of 5%), find the optimal combination of these two stocks. Calculate the expected return, standard deviation, and Sharpe ratio of the resulting tangency portfolio.</em></p>
<div class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: Calculate the components of the optimal weight formula</strong></p>
<p>First, let’s compute the risk premia:</p>
<ul>
<li><span class="math inline">\(E[R_{FB}] - R_f = 0.10 - 0.05 = 0.05\)</span></li>
<li><span class="math inline">\(E[R_{NFLX}] - R_f = 0.15 - 0.05 = 0.10\)</span></li>
</ul>
<p>And the variance terms:</p>
<ul>
<li><span class="math inline">\(\sigma_{FB}^2 = 0.20^2 = 0.04\)</span></li>
<li><span class="math inline">\(\sigma_{NFLX}^2 = 0.25^2 = 0.0625\)</span></li>
</ul>
<p><strong>Step 2: Calculate the numerator</strong></p>
<p><span class="math display">\[\text{Numerator} = (E[R_{FB}] - R_f) \sigma_{NFLX}^2 - (E[R_{NFLX}] - R_f)\text{Cov}(R_{FB}, R_{NFLX})\]</span></p>
<p><span class="math display">\[= (0.05)(0.0625) - (0.10)(0.02)\]</span></p>
<p><span class="math display">\[= 0.003125 - 0.002 = 0.001125\]</span></p>
<p><strong>Step 3: Calculate the denominator</strong></p>
<p><span class="math display">\[\text{Denominator} = (E[R_{FB}] - R_f) \sigma_{NFLX}^2 + (E[R_{NFLX}] - R_f) \sigma_{FB}^2 - (E[R_{FB}] - R_f + E[R_{NFLX}] - R_f)\text{Cov}(R_{FB}, R_{NFLX})\]</span></p>
<p><span class="math display">\[= (0.05)(0.0625) + (0.10)(0.04) - (0.05 + 0.10)(0.02)\]</span></p>
<p><span class="math display">\[= 0.003125 + 0.004 - 0.003 = 0.004125\]</span></p>
<p><strong>Step 4: Calculate optimal weights</strong></p>
<p><span class="math display">\[w_{FB} = \frac{0.001125}{0.004125} = 0.2727 = 27.27\%\]</span></p>
<p><span class="math display">\[w_{NFLX} = 1 - 0.2727 = 0.7273 = 72.73\%\]</span></p>
<p><strong>Step 5: Calculate tangency portfolio characteristics</strong></p>
<p>Expected return: <span class="math display">\[E[R_{tan}] = 0.2727 \times 0.10 + 0.7273 \times 0.15 = 0.02727 + 0.10909 = 0.1364 = 13.64\%\]</span></p>
<p>Variance: <span class="math display">\[\text{Var}(R_{tan}) = (0.2727)^2(0.04) + (0.7273)^2(0.0625) + 2(0.2727)(0.7273)(0.02)\]</span></p>
<p><span class="math display">\[= 0.00297 + 0.03305 + 0.00793 = 0.04395\]</span></p>
<p>Standard deviation: <span class="math display">\[\sigma_{tan} = \sqrt{0.04395} = 0.2096 = 20.96\%\]</span></p>
<p>Sharpe ratio: <span class="math display">\[\text{Sharpe}_{tan} = \frac{0.1364 - 0.05}{0.2096} = \frac{0.0864}{0.2096} = 0.412\]</span></p>
<p><strong>Summary:</strong> The tangency portfolio consists of 27.27% in Facebook and 72.73% in Netflix, with an expected return of 13.64%, standard deviation of 20.96%, and a Sharpe ratio of 0.412. This is the highest Sharpe ratio achievable from any combination of these two stocks.</p>
<p>Note that the Sharpe ratio of 0.412 matches the peak we observed in the table from Example 1, confirming our analytical solution.</p>
</div>
</div>
</div>
</section>
</section>
<section id="portfolio-optimization-with-an-arbitrary-number-of-risky-assets" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="portfolio-optimization-with-an-arbitrary-number-of-risky-assets"><span class="header-section-number">3</span> Portfolio Optimization with an Arbitrary Number of Risky Assets</h2>
<p>Real-world portfolio construction rarely involves just two assets. Investors typically have access to many stocks, bonds, and other securities. The principles we developed for two assets extend naturally to any number of assets, but the notation becomes cumbersome without matrix algebra. This section introduces the matrix representation that makes the general problem tractable.</p>
<section id="matrix-notation-for-portfolio-inputs" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="matrix-notation-for-portfolio-inputs"><span class="header-section-number">3.1</span> Matrix Notation for Portfolio Inputs</h3>
<p>Suppose we have <span class="math inline">\(N\)</span> risky assets, labeled 1 through <span class="math inline">\(N\)</span>. We need to organize three types of information: expected returns, variances, and all pairwise covariances.</p>
<p>The <strong>expected return vector</strong> <span class="math inline">\(\boldsymbol{\mu}\)</span> is an <span class="math inline">\(N \times 1\)</span> column vector containing each asset’s expected return:</p>
<p><span class="math display">\[\boldsymbol{\mu} = \begin{pmatrix} E[R_1] \\ E[R_2] \\ \vdots \\ E[R_N] \end{pmatrix}\]</span></p>
<p>The <strong>variance-covariance matrix</strong> <span class="math inline">\(\boldsymbol{\Sigma}\)</span> is an <span class="math inline">\(N \times N\)</span> matrix that captures all the variance and covariance information. The entry in row <span class="math inline">\(i\)</span> and column <span class="math inline">\(j\)</span> is the covariance between assets <span class="math inline">\(i\)</span> and <span class="math inline">\(j\)</span>. When <span class="math inline">\(i = j\)</span> (on the diagonal), this equals the variance of asset <span class="math inline">\(i\)</span>:</p>
<p><span class="math display">\[\boldsymbol{\Sigma} = \begin{pmatrix} \text{Var}(R_1) &amp; \text{Cov}(R_1, R_2) &amp; \cdots &amp; \text{Cov}(R_1, R_N) \\ \text{Cov}(R_2, R_1) &amp; \text{Var}(R_2) &amp; \cdots &amp; \text{Cov}(R_2, R_N) \\ \vdots &amp; \vdots &amp; \ddots &amp; \vdots \\ \text{Cov}(R_N, R_1) &amp; \text{Cov}(R_N, R_2) &amp; \cdots &amp; \text{Var}(R_N) \end{pmatrix}\]</span></p>
<p>This matrix is symmetric because <span class="math inline">\(\text{Cov}(R_i, R_j) = \text{Cov}(R_j, R_i)\)</span>. The diagonal elements are variances (always positive), while the off-diagonal elements are covariances (which can be positive, negative, or zero).</p>
<p>For optimization, we also need the <strong>excess return vector</strong> (or risk premium vector) <span class="math inline">\(\boldsymbol{\mu}^e\)</span>, which subtracts the risk-free rate from each expected return:</p>
<p><span class="math display">\[\boldsymbol{\mu}^e = \begin{pmatrix} E[R_1] - R_f \\ E[R_2] - R_f \\ \vdots \\ E[R_N] - R_f \end{pmatrix}\]</span></p>
<p>Finally, we define <span class="math inline">\(\mathbf{1}\)</span> as a column vector of <span class="math inline">\(N\)</span> ones, and <span class="math inline">\(\mathbf{1}^T\)</span> as its transpose (a row vector): <span class="math inline">\(\mathbf{1}^T = (1, 1, \ldots, 1)\)</span>.</p>
</section>
<section id="the-tangency-portfolio-with-n-assets" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="the-tangency-portfolio-with-n-assets"><span class="header-section-number">3.2</span> The Tangency Portfolio with N Assets</h3>
<p>The vector of portfolio weights <span class="math inline">\(\mathbf{w}_{tan}\)</span> that maximizes the Sharpe ratio is given by:</p>
<p><span class="math display">\[\mathbf{w}_{tan} = \frac{\boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e}{\mathbf{1}^T \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e}\]</span></p>
<p>Let’s unpack this formula. The numerator <span class="math inline">\(\boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e\)</span> multiplies the inverse of the covariance matrix by the vector of excess returns. The inverse covariance matrix <span class="math inline">\(\boldsymbol{\Sigma}^{-1}\)</span> effectively “adjusts” the excess returns for the risk and correlation structure among assets. Assets that contribute less to portfolio variance (either because they’re low-volatility or because they provide diversification benefits) get higher weights relative to their excess returns.</p>
<p>The denominator <span class="math inline">\(\mathbf{1}^T \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e\)</span> is a scalar—it’s just the sum of all elements in the numerator vector. Dividing by this sum ensures that the weights add up to one, as required for a properly defined portfolio.</p>
<p>This formula is elegant but requires matrix inversion, which becomes computationally intensive as <span class="math inline">\(N\)</span> grows large. In practice, portfolio optimization software handles these calculations, but understanding the structure of the formula helps you interpret results and troubleshoot problems.</p>
<p>The table below summarizes the key matrix objects used in portfolio optimization:</p>
<table class="table">
<colgroup>
<col style="width: 18%">
<col style="width: 27%">
<col style="width: 30%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Dimensions</th>
<th>Description</th>
<th>Elements</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><span class="math inline">\(\boldsymbol{\mu}\)</span></td>
<td><span class="math inline">\(N \times 1\)</span></td>
<td>Expected return vector</td>
<td><span class="math inline">\(E[R_i]\)</span> for each asset</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\boldsymbol{\Sigma}\)</span></td>
<td><span class="math inline">\(N \times N\)</span></td>
<td>Variance-covariance matrix</td>
<td><span class="math inline">\(\text{Var}(R_i)\)</span> on diagonal, <span class="math inline">\(\text{Cov}(R_i, R_j)\)</span> off-diagonal</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\boldsymbol{\Sigma}^{-1}\)</span></td>
<td><span class="math inline">\(N \times N\)</span></td>
<td>Inverse covariance matrix</td>
<td>Used to adjust for risk structure</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\boldsymbol{\mu}^e\)</span></td>
<td><span class="math inline">\(N \times 1\)</span></td>
<td>Excess return vector</td>
<td><span class="math inline">\(E[R_i] - R_f\)</span> for each asset</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(\mathbf{w}_{tan}\)</span></td>
<td><span class="math inline">\(N \times 1\)</span></td>
<td>Tangency portfolio weights</td>
<td>Weight in each asset</td>
</tr>
<tr class="even">
<td><span class="math inline">\(\mathbf{1}\)</span></td>
<td><span class="math inline">\(N \times 1\)</span></td>
<td>Vector of ones</td>
<td>Used to sum weights</td>
</tr>
</tbody>
</table>
<p><strong>Example 3: Tangency Portfolio with Three Assets</strong></p>
<p><em>Consider a portfolio of three stocks with the following characteristics:</em></p>
<table class="table">
<thead>
<tr class="header">
<th>Stock</th>
<th>Expected Return</th>
<th>Standard Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>8%</td>
<td>15%</td>
</tr>
<tr class="even">
<td>B</td>
<td>12%</td>
<td>20%</td>
</tr>
<tr class="odd">
<td>C</td>
<td>16%</td>
<td>30%</td>
</tr>
</tbody>
</table>
<p><em>The correlation matrix is:</em></p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>A</th>
<th>B</th>
<th>C</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>1.0</td>
<td>0.3</td>
<td>0.2</td>
</tr>
<tr class="even">
<td>B</td>
<td>0.3</td>
<td>1.0</td>
<td>0.5</td>
</tr>
<tr class="odd">
<td>C</td>
<td>0.2</td>
<td>0.5</td>
<td>1.0</td>
</tr>
</tbody>
</table>
<p><em>The risk-free rate is 4%. Find the tangency portfolio weights and calculate its expected return, standard deviation, and Sharpe ratio.</em></p>
<div class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: Set up the matrix inputs</strong></p>
<p>Expected return vector: <span class="math display">\[\boldsymbol{\mu} = \begin{pmatrix} 0.08 \\ 0.12 \\ 0.16 \end{pmatrix}\]</span></p>
<p>Excess return vector: <span class="math display">\[\boldsymbol{\mu}^e = \begin{pmatrix} 0.08 - 0.04 \\ 0.12 - 0.04 \\ 0.16 - 0.04 \end{pmatrix} = \begin{pmatrix} 0.04 \\ 0.08 \\ 0.12 \end{pmatrix}\]</span></p>
<p><strong>Step 2: Convert correlations to covariances</strong></p>
<p>Recall that <span class="math inline">\(\text{Cov}(R_i, R_j) = \rho_{ij} \sigma_i \sigma_j\)</span></p>
<ul>
<li><span class="math inline">\(\text{Cov}(A,B) = 0.3 \times 0.15 \times 0.20 = 0.009\)</span></li>
<li><span class="math inline">\(\text{Cov}(A,C) = 0.2 \times 0.15 \times 0.30 = 0.009\)</span></li>
<li><span class="math inline">\(\text{Cov}(B,C) = 0.5 \times 0.20 \times 0.30 = 0.030\)</span></li>
</ul>
<p>Variance-covariance matrix: <span class="math display">\[\boldsymbol{\Sigma} = \begin{pmatrix} 0.0225 &amp; 0.009 &amp; 0.009 \\ 0.009 &amp; 0.04 &amp; 0.03 \\ 0.009 &amp; 0.03 &amp; 0.09 \end{pmatrix}\]</span></p>
<p><strong>Step 3: Compute the inverse covariance matrix</strong></p>
<p>Using matrix inversion (typically done with software): <span class="math display">\[\boldsymbol{\Sigma}^{-1} = \begin{pmatrix} 50.420 &amp; -6.723 &amp; -1.681 \\ -6.723 &amp; 37.815 &amp; -10.504 \\ -1.681 &amp; -10.504 &amp; 15.126 \end{pmatrix}\]</span></p>
<p><strong>Step 4: Calculate <span class="math inline">\(\boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e\)</span></strong></p>
<p><span class="math display">\[\boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e = \begin{pmatrix} 50.420 &amp; -6.723 &amp; -1.681 \\ -6.723 &amp; 37.815 &amp; -10.504 \\ -1.681 &amp; -10.504 &amp; 15.126 \end{pmatrix} \begin{pmatrix} 0.04 \\ 0.08 \\ 0.12 \end{pmatrix}\]</span></p>
<p><span class="math display">\[= \begin{pmatrix} 50.420(0.04) + (-6.723)(0.08) + (-1.681)(0.12) \\ (-6.723)(0.04) + 37.815(0.08) + (-10.504)(0.12) \\ (-1.681)(0.04) + (-10.504)(0.08) + 15.126(0.12) \end{pmatrix}\]</span></p>
<p><span class="math display">\[= \begin{pmatrix} 2.017 - 0.538 - 0.202 \\ -0.269 + 3.025 - 1.260 \\ -0.067 - 0.840 + 1.815 \end{pmatrix} = \begin{pmatrix} 1.277 \\ 1.496 \\ 0.908 \end{pmatrix}\]</span></p>
<p><strong>Step 5: Calculate the denominator</strong></p>
<p><span class="math display">\[\mathbf{1}^T \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e = 1.277 + 1.496 + 0.908 = 3.681\]</span></p>
<p><strong>Step 6: Calculate tangency portfolio weights</strong></p>
<p><span class="math display">\[\mathbf{w}_{tan} = \frac{1}{3.681} \begin{pmatrix} 1.277 \\ 1.496 \\ 0.908 \end{pmatrix} = \begin{pmatrix} 0.347 \\ 0.406 \\ 0.247 \end{pmatrix}\]</span></p>
<p>So the tangency portfolio consists of 34.7% in Stock A, 40.6% in Stock B, and 24.7% in Stock C.</p>
<p><strong>Step 7: Calculate portfolio characteristics</strong></p>
<p>Expected return: <span class="math display">\[E[R_{tan}] = 0.347(0.08) + 0.406(0.12) + 0.247(0.16) = 0.0278 + 0.0487 + 0.0395 = 0.116 = 11.6\%\]</span></p>
<p>Portfolio variance (using matrix multiplication <span class="math inline">\(\mathbf{w}^T \boldsymbol{\Sigma} \mathbf{w}\)</span>): <span class="math display">\[\text{Var}(R_{tan}) = 0.0209\]</span></p>
<p>Standard deviation: <span class="math display">\[\sigma_{tan} = \sqrt{0.0209} = 0.1446 = 14.46\%\]</span></p>
<p>Sharpe ratio: <span class="math display">\[\text{Sharpe}_{tan} = \frac{0.116 - 0.04}{0.1446} = \frac{0.076}{0.1446} = 0.526\]</span></p>
<p><strong>Summary:</strong> The tangency portfolio has weights of 34.7% in A, 40.6% in B, and 24.7% in C, with an expected return of 11.6%, standard deviation of 14.46%, and Sharpe ratio of 0.526.</p>
</div>
</div>
</div>
</section>
</section>
<section id="key-takeaways" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="key-takeaways"><span class="header-section-number">4</span> Key Takeaways</h2>
<p>Portfolio optimization addresses one of the most fundamental questions in investing: given a set of risky assets with known expected returns, volatilities, and correlations, how should you combine them to achieve the best risk-adjusted performance? The answer is the tangency portfolio—the unique combination of assets that maximizes the Sharpe ratio.</p>
<p>The journey from two assets to many assets reveals both the power and complexity of diversification. With just two assets, we can visualize the investment opportunity set as a curve in mean-volatility space, and the tangency portfolio appears where the Capital Allocation Line touches this curve at its steepest point. The optimal weight formula, while algebraically complex, yields a closed-form solution that depends on excess returns, variances, and the covariance between assets.</p>
<p>When we extend to multiple assets, matrix algebra becomes essential. The expected returns form a vector, the variances and covariances form a symmetric matrix, and the tangency portfolio weights emerge from multiplying the inverse covariance matrix by the excess return vector. This mathematical structure reveals something profound: the optimal weights depend not just on each asset’s individual attractiveness (its excess return) but on how each asset interacts with all other assets through the covariance structure.</p>
<p>Perhaps the most important insight from portfolio optimization is the separation principle: the tangency portfolio is the same for all investors, regardless of their risk tolerance. A conservative investor and an aggressive investor will both want to hold this same mix of risky assets—they differ only in how much they allocate to this risky portfolio versus the risk-free asset. This means that once you’ve identified the tangency portfolio, the only remaining decision is personal: how much risk are you willing to bear? We explore this capital allocation decision in depth in the next lecture.</p>
</section>
<section id="key-formulas-summary" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="key-formulas-summary"><span class="header-section-number">5</span> Key Formulas Summary</h2>
<table class="table">
<colgroup>
<col style="width: 29%">
<col style="width: 29%">
<col style="width: 41%">
</colgroup>
<thead>
<tr class="header">
<th>Concept</th>
<th>Formula</th>
<th>When to Use</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Portfolio Expected Return (2 assets)</td>
<td><span class="math inline">\(E[R_P] = w_A E[R_A] + w_B E[R_B]\)</span></td>
<td>Calculate expected return of any two-asset portfolio</td>
</tr>
<tr class="even">
<td>Portfolio Variance (2 assets)</td>
<td><span class="math inline">\(\text{Var}(R_P) = w_A^2 \text{Var}(R_A) + w_B^2 \text{Var}(R_B) + 2 w_A w_B \text{Cov}(R_A, R_B)\)</span></td>
<td>Calculate risk of any two-asset portfolio</td>
</tr>
<tr class="odd">
<td>Optimal Weight in Asset A</td>
<td><span class="math inline">\(w_A = \frac{(E[R_A] - R_f) \sigma_B^2 - (E[R_B] - R_f)\text{Cov}(R_A, R_B)}{(E[R_A] - R_f) \sigma_B^2 + (E[R_B] - R_f) \sigma_A^2 - (E[R_A] - R_f + E[R_B] - R_f)\text{Cov}(R_A, R_B)}\)</span></td>
<td>Find tangency portfolio weights with two assets</td>
</tr>
<tr class="even">
<td>Tangency Portfolio Weights (N assets)</td>
<td><span class="math inline">\(\mathbf{w}_{tan} = \frac{\boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e}{\mathbf{1}^T \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e}\)</span></td>
<td>Find tangency portfolio weights with any number of assets</td>
</tr>
<tr class="odd">
<td>Sharpe Ratio</td>
<td><span class="math inline">\(\text{Sharpe} = \frac{E[R_P] - R_f}{\sigma_P}\)</span></td>
<td>Evaluate risk-adjusted performance of any portfolio</td>
</tr>
<tr class="even">
<td>Covariance from Correlation</td>
<td><span class="math inline">\(\text{Cov}(R_i, R_j) = \rho_{ij} \sigma_i \sigma_j\)</span></td>
<td>Convert between correlation and covariance</td>
</tr>
</tbody>
</table>
</section>
<section id="practice-problems" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="practice-problems"><span class="header-section-number">6</span> Practice Problems</h2>
<p><strong>Practice Problem 1: Investment Opportunity Set</strong></p>
<p><em>You are analyzing two ETFs: a bond fund (BND) and a stock fund (VTI). The bond fund has an expected return of 4% with a standard deviation of 8%, while the stock fund has an expected return of 10% with a standard deviation of 18%. The covariance between their returns is 0.005, and the risk-free rate is 2%. Calculate the expected return, standard deviation, and Sharpe ratio for portfolios with the following weights in BND: 0%, 25%, 50%, 75%, and 100%.</em></p>
<div class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Given information:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th>Parameter</th>
<th>BND</th>
<th>VTI</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Expected Return</td>
<td>4%</td>
<td>10%</td>
</tr>
<tr class="even">
<td>Standard Deviation</td>
<td>8%</td>
<td>18%</td>
</tr>
<tr class="odd">
<td>Covariance</td>
<td>0.005</td>
<td></td>
</tr>
<tr class="even">
<td>Risk-free rate</td>
<td>2%</td>
<td></td>
</tr>
</tbody>
</table>
<p><strong>Portfolio calculations:</strong></p>
<p><em>Portfolio 1: <span class="math inline">\(w_{BND} = 0\%\)</span>, <span class="math inline">\(w_{VTI} = 100\%\)</span></em></p>
<p><span class="math display">\[E[R_P] = 0(0.04) + 1(0.10) = 10\%\]</span></p>
<p><span class="math display">\[\text{Var}(R_P) = 0^2(0.0064) + 1^2(0.0324) + 2(0)(1)(0.005) = 0.0324\]</span></p>
<p><span class="math display">\[\sigma_P = \sqrt{0.0324} = 18\%\]</span></p>
<p><span class="math display">\[\text{Sharpe} = \frac{0.10 - 0.02}{0.18} = 0.444\]</span></p>
<p><em>Portfolio 2: <span class="math inline">\(w_{BND} = 25\%\)</span>, <span class="math inline">\(w_{VTI} = 75\%\)</span></em></p>
<p><span class="math display">\[E[R_P] = 0.25(0.04) + 0.75(0.10) = 0.01 + 0.075 = 8.5\%\]</span></p>
<p><span class="math display">\[\text{Var}(R_P) = 0.25^2(0.0064) + 0.75^2(0.0324) + 2(0.25)(0.75)(0.005)\]</span></p>
<p><span class="math display">\[= 0.0004 + 0.0182 + 0.00188 = 0.0205\]</span></p>
<p><span class="math display">\[\sigma_P = \sqrt{0.0205} = 14.32\%\]</span></p>
<p><span class="math display">\[\text{Sharpe} = \frac{0.085 - 0.02}{0.1432} = 0.454\]</span></p>
<p><em>Portfolio 3: <span class="math inline">\(w_{BND} = 50\%\)</span>, <span class="math inline">\(w_{VTI} = 50\%\)</span></em></p>
<p><span class="math display">\[E[R_P] = 0.50(0.04) + 0.50(0.10) = 7\%\]</span></p>
<p><span class="math display">\[\text{Var}(R_P) = 0.50^2(0.0064) + 0.50^2(0.0324) + 2(0.50)(0.50)(0.005)\]</span></p>
<p><span class="math display">\[= 0.0016 + 0.0081 + 0.0025 = 0.0122\]</span></p>
<p><span class="math display">\[\sigma_P = \sqrt{0.0122} = 11.05\%\]</span></p>
<p><span class="math display">\[\text{Sharpe} = \frac{0.07 - 0.02}{0.1105} = 0.452\]</span></p>
<p><em>Portfolio 4: <span class="math inline">\(w_{BND} = 75\%\)</span>, <span class="math inline">\(w_{VTI} = 25\%\)</span></em></p>
<p><span class="math display">\[E[R_P] = 0.75(0.04) + 0.25(0.10) = 5.5\%\]</span></p>
<p><span class="math display">\[\text{Var}(R_P) = 0.75^2(0.0064) + 0.25^2(0.0324) + 2(0.75)(0.25)(0.005)\]</span></p>
<p><span class="math display">\[= 0.0036 + 0.0020 + 0.00188 = 0.00748\]</span></p>
<p><span class="math display">\[\sigma_P = \sqrt{0.00748} = 8.65\%\]</span></p>
<p><span class="math display">\[\text{Sharpe} = \frac{0.055 - 0.02}{0.0865} = 0.405\]</span></p>
<p><em>Portfolio 5: <span class="math inline">\(w_{BND} = 100\%\)</span>, <span class="math inline">\(w_{VTI} = 0\%\)</span></em></p>
<p><span class="math display">\[E[R_P] = 1(0.04) + 0(0.10) = 4\%\]</span></p>
<p><span class="math display">\[\sigma_P = 8\%\]</span></p>
<p><span class="math display">\[\text{Sharpe} = \frac{0.04 - 0.02}{0.08} = 0.250\]</span></p>
<p><strong>Summary table:</strong></p>
<table class="table">
<thead>
<tr class="header">
<th><span class="math inline">\(w_{BND}\)</span></th>
<th><span class="math inline">\(w_{VTI}\)</span></th>
<th><span class="math inline">\(E[R_P]\)</span></th>
<th><span class="math inline">\(\sigma_P\)</span></th>
<th>Sharpe</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>0%</td>
<td>100%</td>
<td>10.00%</td>
<td>18.00%</td>
<td>0.444</td>
</tr>
<tr class="even">
<td>25%</td>
<td>75%</td>
<td>8.50%</td>
<td>14.32%</td>
<td>0.454</td>
</tr>
<tr class="odd">
<td>50%</td>
<td>50%</td>
<td>7.00%</td>
<td>11.05%</td>
<td>0.452</td>
</tr>
<tr class="even">
<td>75%</td>
<td>25%</td>
<td>5.50%</td>
<td>8.65%</td>
<td>0.405</td>
</tr>
<tr class="odd">
<td>100%</td>
<td>0%</td>
<td>4.00%</td>
<td>8.00%</td>
<td>0.250</td>
</tr>
</tbody>
</table>
<p>The highest Sharpe ratio (0.454) occurs around 25% bonds and 75% stocks, suggesting the tangency portfolio is close to this allocation.</p>
</div>
</div>
</div>
<p><strong>Practice Problem 2: Two-Asset Tangency Portfolio</strong></p>
<p><em>Using the BND and VTI data from Practice Problem 1, calculate the exact tangency portfolio weights. Then compute the expected return, standard deviation, and Sharpe ratio of this optimal portfolio.</em></p>
<div class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Given:</strong> <span class="math inline">\(E[R_{BND}] = 4\%\)</span>, <span class="math inline">\(E[R_{VTI}] = 10\%\)</span>, <span class="math inline">\(\sigma_{BND} = 8\%\)</span>, <span class="math inline">\(\sigma_{VTI} = 18\%\)</span>, <span class="math inline">\(\text{Cov} = 0.005\)</span>, <span class="math inline">\(R_f = 2\%\)</span></p>
<p><strong>Step 1: Calculate components</strong></p>
<p>Risk premia:</p>
<ul>
<li><span class="math inline">\(E[R_{BND}] - R_f = 0.04 - 0.02 = 0.02\)</span></li>
<li><span class="math inline">\(E[R_{VTI}] - R_f = 0.10 - 0.02 = 0.08\)</span></li>
</ul>
<p>Variances:</p>
<ul>
<li><span class="math inline">\(\sigma_{BND}^2 = 0.0064\)</span></li>
<li><span class="math inline">\(\sigma_{VTI}^2 = 0.0324\)</span></li>
</ul>
<p><strong>Step 2: Calculate numerator</strong></p>
<p><span class="math display">\[\text{Num} = (E[R_{BND}] - R_f)\sigma_{VTI}^2 - (E[R_{VTI}] - R_f)\text{Cov}\]</span></p>
<p><span class="math display">\[= (0.02)(0.0324) - (0.08)(0.005)\]</span></p>
<p><span class="math display">\[= 0.000648 - 0.0004 = 0.000248\]</span></p>
<p><strong>Step 3: Calculate denominator</strong></p>
<p><span class="math display">\[\text{Denom} = (E[R_{BND}] - R_f)\sigma_{VTI}^2 + (E[R_{VTI}] - R_f)\sigma_{BND}^2 - (E[R_{BND}] - R_f + E[R_{VTI}] - R_f)\text{Cov}\]</span></p>
<p><span class="math display">\[= (0.02)(0.0324) + (0.08)(0.0064) - (0.02 + 0.08)(0.005)\]</span></p>
<p><span class="math display">\[= 0.000648 + 0.000512 - 0.0005 = 0.00066\]</span></p>
<p><strong>Step 4: Calculate optimal weights</strong></p>
<p><span class="math display">\[w_{BND} = \frac{0.000248}{0.00066} = 0.376 = 37.6\%\]</span></p>
<p><span class="math display">\[w_{VTI} = 1 - 0.376 = 0.624 = 62.4\%\]</span></p>
<p><strong>Step 5: Calculate portfolio characteristics</strong></p>
<p>Expected return: <span class="math display">\[E[R_{tan}] = 0.376(0.04) + 0.624(0.10) = 0.01504 + 0.0624 = 7.74\%\]</span></p>
<p>Variance: <span class="math display">\[\text{Var}(R_{tan}) = 0.376^2(0.0064) + 0.624^2(0.0324) + 2(0.376)(0.624)(0.005)\]</span></p>
<p><span class="math display">\[= 0.000905 + 0.01262 + 0.00235 = 0.01588\]</span></p>
<p>Standard deviation: <span class="math display">\[\sigma_{tan} = \sqrt{0.01588} = 12.60\%\]</span></p>
<p>Sharpe ratio: <span class="math display">\[\text{Sharpe}_{tan} = \frac{0.0774 - 0.02}{0.1260} = \frac{0.0574}{0.1260} = 0.456\]</span></p>
<p><strong>Summary:</strong> The tangency portfolio consists of 37.6% in BND and 62.4% in VTI, with an expected return of 7.74%, standard deviation of 12.60%, and a maximum Sharpe ratio of 0.456.</p>
</div>
</div>
</div>
<p><strong>Practice Problem 3: Three-Asset Tangency Portfolio</strong></p>
<p><em>Consider three assets with the following characteristics:</em></p>
<table class="table">
<thead>
<tr class="header">
<th>Asset</th>
<th>Expected Return</th>
<th>Standard Deviation</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>X</td>
<td>6%</td>
<td>12%</td>
</tr>
<tr class="even">
<td>Y</td>
<td>10%</td>
<td>18%</td>
</tr>
<tr class="odd">
<td>Z</td>
<td>14%</td>
<td>25%</td>
</tr>
</tbody>
</table>
<p><em>The correlation matrix is:</em></p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>X</th>
<th>Y</th>
<th>Z</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>X</td>
<td>1.0</td>
<td>0.4</td>
<td>0.2</td>
</tr>
<tr class="even">
<td>Y</td>
<td>0.4</td>
<td>1.0</td>
<td>0.6</td>
</tr>
<tr class="odd">
<td>Z</td>
<td>0.2</td>
<td>0.6</td>
<td>1.0</td>
</tr>
</tbody>
</table>
<p><em>The risk-free rate is 3%. Calculate the tangency portfolio weights and the portfolio’s expected return, standard deviation, and Sharpe ratio.</em></p>
<div class="callout callout-style-default callout-note callout-titled" title="Solution">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Solution
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p><strong>Step 1: Set up vectors and matrices</strong></p>
<p>Expected return vector: <span class="math display">\[\boldsymbol{\mu} = \begin{pmatrix} 0.06 \\ 0.10 \\ 0.14 \end{pmatrix}\]</span></p>
<p>Excess return vector: <span class="math display">\[\boldsymbol{\mu}^e = \begin{pmatrix} 0.06 - 0.03 \\ 0.10 - 0.03 \\ 0.14 - 0.03 \end{pmatrix} = \begin{pmatrix} 0.03 \\ 0.07 \\ 0.11 \end{pmatrix}\]</span></p>
<p><strong>Step 2: Convert correlations to covariances</strong></p>
<ul>
<li><span class="math inline">\(\text{Cov}(X,Y) = 0.4 \times 0.12 \times 0.18 = 0.00864\)</span></li>
<li><span class="math inline">\(\text{Cov}(X,Z) = 0.2 \times 0.12 \times 0.25 = 0.006\)</span></li>
<li><span class="math inline">\(\text{Cov}(Y,Z) = 0.6 \times 0.18 \times 0.25 = 0.027\)</span></li>
</ul>
<p>Variance-covariance matrix: <span class="math display">\[\boldsymbol{\Sigma} = \begin{pmatrix} 0.0144 &amp; 0.00864 &amp; 0.006 \\ 0.00864 &amp; 0.0324 &amp; 0.027 \\ 0.006 &amp; 0.027 &amp; 0.0625 \end{pmatrix}\]</span></p>
<p><strong>Step 3: Compute inverse covariance matrix</strong></p>
<p><span class="math display">\[\boldsymbol{\Sigma}^{-1} = \begin{pmatrix} 82.18 &amp; -14.52 &amp; -2.42 \\ -14.52 &amp; 50.81 &amp; -18.15 \\ -2.42 &amp; -18.15 &amp; 25.60 \end{pmatrix}\]</span></p>
<p><strong>Step 4: Calculate <span class="math inline">\(\boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e\)</span></strong></p>
<p><span class="math display">\[\boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e = \begin{pmatrix} 82.18(0.03) + (-14.52)(0.07) + (-2.42)(0.11) \\ (-14.52)(0.03) + 50.81(0.07) + (-18.15)(0.11) \\ (-2.42)(0.03) + (-18.15)(0.07) + 25.60(0.11) \end{pmatrix}\]</span></p>
<p><span class="math display">\[= \begin{pmatrix} 2.465 - 1.016 - 0.266 \\ -0.436 + 3.557 - 1.997 \\ -0.073 - 1.271 + 2.816 \end{pmatrix} = \begin{pmatrix} 1.183 \\ 1.124 \\ 1.472 \end{pmatrix}\]</span></p>
<p><strong>Step 5: Calculate denominator and weights</strong></p>
<p><span class="math display">\[\mathbf{1}^T \boldsymbol{\Sigma}^{-1} \boldsymbol{\mu}^e = 1.183 + 1.124 + 1.472 = 3.779\]</span></p>
<p><span class="math display">\[\mathbf{w}_{tan} = \frac{1}{3.779} \begin{pmatrix} 1.183 \\ 1.124 \\ 1.472 \end{pmatrix} = \begin{pmatrix} 0.313 \\ 0.297 \\ 0.390 \end{pmatrix}\]</span></p>
<p>The tangency portfolio: 31.3% in X, 29.7% in Y, and 39.0% in Z.</p>
<p><strong>Step 6: Calculate portfolio characteristics</strong></p>
<p>Expected return: <span class="math display">\[E[R_{tan}] = 0.313(0.06) + 0.297(0.10) + 0.390(0.14) = 0.01878 + 0.0297 + 0.0546 = 10.31\%\]</span></p>
<p>Portfolio variance (computing <span class="math inline">\(\mathbf{w}^T \boldsymbol{\Sigma} \mathbf{w}\)</span>): <span class="math display">\[\text{Var}(R_{tan}) = 0.0192\]</span></p>
<p>Standard deviation: <span class="math display">\[\sigma_{tan} = \sqrt{0.0192} = 13.86\%\]</span></p>
<p>Sharpe ratio: <span class="math display">\[\text{Sharpe}_{tan} = \frac{0.1031 - 0.03}{0.1386} = \frac{0.0731}{0.1386} = 0.527\]</span></p>
<p><strong>Summary:</strong> The tangency portfolio consists of 31.3% in X, 29.7% in Y, and 39.0% in Z, with an expected return of 10.31%, standard deviation of 13.86%, and Sharpe ratio of 0.527.</p>
</div>
</div>
</div>
</section>
<section id="ask-an-llm" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="ask-an-llm"><span class="header-section-number">7</span> Ask an LLM</h2>
<p>Here are three questions you might ask an AI assistant to deepen your understanding of these concepts:</p>
<ul>
<li>Can you walk me through an intuitive explanation of why the tangency portfolio is the same for all investors regardless of their risk aversion? What assumptions are required for this result to hold?</li>
<li>How would the tangency portfolio weights change if one asset’s correlation with the others suddenly increased? Can you give me a numerical example showing this effect?</li>
<li>In practice, we estimate expected returns and covariances from historical data, which introduces estimation error. How sensitive is the tangency portfolio to errors in these inputs, and what techniques do practitioners use to make portfolio optimization more robust?</li>
<li>What happens to the tangency portfolio formula if one of the assets is the risk-free asset? Can you show mathematically why this creates a problem and how it relates to the Capital Market Line?</li>
<li>How does the number of assets in a portfolio affect the benefits of diversification? Is there a point of diminishing returns, and if so, why?</li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>